localmonero/funds/urls.py
from django.urls import path
from  .views import fund_localmonero_account ,withdraw_localmonero ,withdraw_btc ,withdraw_xmr 

app_name = 'funds'

urlpatterns = [
 
    path('', fund_localmonero_account, name='fund_localmonero_account'),
    path('withdraw', withdraw_localmonero, name='withdraw_localmonero'),
    path('withdraw_btc/', withdraw_btc, name='withdraw_btc'),
    path('withdraw_xmr/', withdraw_xmr, name='withdraw_xmr'),
 
]

localmonero/localmonero/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('web.urls')),
    path('user/', include('user.urls')),
    path('offer/', include('offer.urls')),
    path('funds/', include('funds.urls')),
    path('',include('home.urls')), 
    
]

localmonero/offer/urls.py
from django.urls import path
from .views import new_offer, offer_list, offer_detail, offer_edit, offer_delete, offer_search,init_transaction

app_name = 'offer'
urlpatterns = [
    path('new/', new_offer, name='new_offer'),
    path('', offer_list, name='offer_list'),
    path('<int:offer_id>/', offer_detail, name='offer_detail'),
    path('<int:offer_id>/edit/', offer_edit, name='offer_edit'),
    path('<int:offer_id>/delete/', offer_delete, name='offer_delete'),
    path('search/', offer_search, name='offer_search'),
    path('buy/<int:offer_id>/', init_transaction, name='init_transction')
]

localmonero/web/urls.py
from web.views import health_check, isMoneroUp, isBitcoinUp, getBalance,createWalletBTC,sendBTC,checkBalanceByAddressBTC

from django.urls import path

app_name = 'web'

urlpatterns = [
    
    path('health_check/', health_check, name='health_check'),
    path('isMoneroUp/', isMoneroUp, name='isMoneroUp'),
    path('isBitcoinUp/', isBitcoinUp, name='isBitcoinUp'),
    path('getBalance/', getBalance, name='getBalance'),
    path('createWalletBTC/', createWalletBTC, name='createWalletBTC'),
    path('sendBTC/', sendBTC, name='sendBTC'),
    path('checkBalanceByAddressBTC/', checkBalanceByAddressBTC, name='checkBalanceByAddressBTC'),
    
]

localmonero/localmonero/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}LocalMonero{% endblock %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            display: flex;
        }
        .sidebar {
            width: 250px;
            position: fixed;
            top: 0;
            left: 0;
            height: 100%;
            background-color: #f8f9fa;
            padding-top: 20px;
        }
        .content {
            margin-left: 250px;
            padding: 20px;
        }
        .nav-link.active {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="sidebar">
        <h3 class="text-center">LocalMonero</h3>
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'offer:offer_list' %}">
                    <i class="fas fa-list"></i> Offers
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'offer:new_offer' %}">
                    <i class="fas fa-plus-circle"></i> New Offer
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'offer:offer_search' %}">
                    <i class="fas fa-search"></i> Search Offers
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'funds:withdraw_xmr' %}">
                    <i class="fas fa-arrow-circle-right"></i> Withdraw XMR
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'funds:withdraw_btc' %}">
                    <i class="fas fa-arrow-circle-right"></i> Withdraw BTC
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'funds:withdraw_localmonero' %}">
                    <i class="fas fa-arrow-circle-right"></i> Withdraw LocalMonero
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'funds:fund_localmonero_account' %}">
                    <i class="fas fa-dollar-sign"></i> Fund Account
                </a>
            </li>
        </ul>
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>