localmonero/localmonero/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('web.urls')),
    path('user/', include('user.urls')),
    path('offer/', include('offer.urls')),
    path('funds/', include('funds.urls')),
    path('',include('home.urls')), 
    
]

localmonero/offer/urls.py
from django.urls import path
from .views import new_offer, offer_list, offer_detail, offer_edit, offer_delete, offer_search,init_transaction

app_name = 'offer'
urlpatterns = [
    path('new/', new_offer, name='new_offer'),
    path('', offer_list, name='offer_list'),
    path('<int:offer_id>/', offer_detail, name='offer_detail'),
    path('<int:offer_id>/edit/', offer_edit, name='offer_edit'),
    path('<int:offer_id>/delete/', offer_delete, name='offer_delete'),
    path('search/', offer_search, name='offer_search'),
    path('buy/<int:offer_id>/', init_transaction, name='init_transction')
]

localmonero/web/urls.py
from web.views import health_check, isMoneroUp, isBitcoinUp, getBalance,createWalletBTC,sendBTC,checkBalanceByAddressBTC

from django.urls import path

app_name = 'web'

urlpatterns = [
    
    path('health_check/', health_check, name='health_check'),
    path('isMoneroUp/', isMoneroUp, name='isMoneroUp'),
    path('isBitcoinUp/', isBitcoinUp, name='isBitcoinUp'),
    path('getBalance/', getBalance, name='getBalance'),
    path('createWalletBTC/', createWalletBTC, name='createWalletBTC'),
    path('sendBTC/', sendBTC, name='sendBTC'),
    path('checkBalanceByAddressBTC/', checkBalanceByAddressBTC, name='checkBalanceByAddressBTC'),
    
]

localmonero/offer/models.py
from django.db import models
from django.contrib.auth.models import User

class Offer(models.Model):
    OFFER_TYPE_CHOICES = [
        ('buy', 'Buy'),
        ('sell', 'Sell')
    ]

    PAYMENT_METHOD_CHOICES = [
        ('btc', 'Bitcoin (BTC)'),
        ('xmr', 'Monero (XMR)'),
        ('localmonero', 'LocalMonero')
    ]

    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    offer_type = models.CharField(max_length=4, choices=OFFER_TYPE_CHOICES)
    cryptocurrency = models.CharField(max_length=15, choices=PAYMENT_METHOD_CHOICES)
    amount = models.DecimalField(max_digits=10, decimal_places=8)
    against = models.CharField(max_length=15, choices=PAYMENT_METHOD_CHOICES, default='localmonero')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=15, default='',choices=[('active','Active'),('pending','Pending'),('completed','Completed'),('cancelled','Cancelled')])
    updated = models.DateTimeField(auto_now=True)
    details = models.TextField()
    txid = models.CharField(max_length=100, blank=True)
    
    def __str__(self):
        return f"{self.offer_type} {self.amount} {self.cryptocurrency} for {self.price}"



class Transaction(models.Model):
    offer = models.ForeignKey(Offer, on_delete=models.CASCADE)
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=15, default='',choices=[('pending','Pending'),('completed','Completed')])
    updated = models.DateTimeField(auto_now=True)
    coin = models.CharField(max_length=15, choices=[('btc','BTC'),('xmr','XMR')])
    txid = models.CharField(max_length=100, blank=True)
    
    def __str__(self):
        return f"{self.offer} {self.buyer} {self.status}"

localmonero/offer/forms.py
from django import forms
from .models import Offer

class OfferForm(forms.ModelForm):
    class Meta:
        model = Offer
        fields = ['offer_type', 'cryptocurrency', 'amount', 'price', 'details', 'against']

localmonero/offer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Offer, Transaction
from web.utils.Monero import withdraw as send_monero
from web.utils.btc import send_to_address
from .forms import OfferForm
from django.contrib.auth.models import User

def get_addresses(crypto, offer):
    if crypto == 'BTC':
        website_address = User.objects.get(username='bader').profile.btc_address
        user_address = offer.seller.profile.btc_address
    elif crypto == 'XMR':
        website_address = User.objects.get(username='bader').profile.xmr_address
        user_address = offer.seller.profile.xmr_address
    return website_address, user_address


def perform_transaction(offer):
    offer.cryptocurrency = offer.cryptocurrency.upper()
    offer.cryptocurrency = offer.cryptocurrency if offer.offer_type == 'SELL' else offer.against
    website_address, user_address = get_addresses(offer.cryptocurrency,offer)
    if offer.cryptocurrency == 'BTC':
        txid = send_to_address(user_address, website_address, offer.amount)
    elif offer.cryptocurrency == 'XMR':
        txid = send_monero(user_address, website_address, offer.amount)
    if txid:
        offer.status = 'ACTIVE'
        offer.txid = txid
        offer.save()

def threading_perform_transaction(offer):
    from threading import Thread
    t = Thread(target=perform_transaction, args=(offer,))
    t.start()

@login_required
def new_offer(request):
    if request.method == 'POST':
        form = OfferForm(request.POST)
        if form.is_valid():
            offer = form.save(commit=False)
            offer.seller = request.user
            offer.status = 'PENDING'
            offer.save()
            threading_perform_transaction(offer)
            return redirect('offer:offer_detail', offer_id=offer.id)
            
    else:
        form = OfferForm()
    return render(request, 'offer/new_offer.html', {'form': form})

@login_required
def offer_list(request):
    offer = Offer.objects.all()
    return render(request, 'offer/offer_list.html', {'offers': offer,'count':offer.count()})

@login_required
def offer_detail(request, offer_id):
    offer = get_object_or_404(Offer, id=offer_id)
    return render(request, 'offer/offer_detail.html', {'offer': offer})

@login_required
def offer_edit(request, offer_id):
    offer = get_object_or_404(Offer, id=offer_id)
    if offer.seller != request.user:
        return redirect('offer:offer_list')
    if request.method == 'POST':
        form = OfferForm(request.POST, instance=offer)
        if form.is_valid():
            form.save()
            return redirect('offer:offer_detail', offer_id=offer.id)
    else:
        form = OfferForm(instance=offer)
    return render(request, 'offer/offer_edit.html', {'form': form})

@login_required
def offer_delete(request, offer_id):
    offer = get_object_or_404(Offer, id=offer_id)
    if offer.seller != request.user:
        return redirect('offer:offer_list')
    offer.delete()
    return redirect('offer:offer_list')

@login_required
def offer_search(request):
    if request.method == 'GET':
        query = request.GET.get('query')
        if not query:
            return render(request, 'offer/offer_search.html')
        results = Offer.objects.filter(details__icontains=query)
        return render(request, 'offer/offer_search.html', {'results': results, 'query': query})
    return render(request, 'offer/offer_search.html')

def complete_transaction(transaction):
    transaction.status = 'COMPLETED'
    transaction.save()
    offer = transaction.offer
    offer.status = 'COMPLETED' if offer.amount == transaction.amount else 'ACTIVE'
    offer.amount -= transaction.amount
    offer.save()
    close_deal(transaction)

#? ANything wrong with this function?

def close_deal(transaction):
    #send money from website to the one who bought the offer
    
    website_address, seller_address = get_addresses(transaction.coin, transaction.offer)
    #TODO: Implement the send_to_address function
def threading_complete_transaction(transaction):
    from threading import Thread
    t = Thread(target=complete_transaction, args=(transaction,))
    t.start()

@login_required
def init_transaction(request, offer_id):
    offer = get_object_or_404(Offer, id=offer_id)
    if offer.seller == request.user:
        return redirect('offer:offer_detail', offer_id=offer.id)

    if request.method == 'GET':
        return render(request, 'offer/init_transaction.html', {'offer': offer})

    if request.method == 'POST':
        amount = request.POST.get('amount')
        coin = request.POST.get('coin')

        if amount is None or coin not in ['BTC', 'XMR']:
            return render(request, 'offer/init_transaction.html', {'offer': offer, 'error': 'Invalid amount or coin'})
        if float(amount) > offer.amount:
            return render(request, 'offer/init_transaction.html', {'offer': offer, 'error': 'Amount is greater than the offer'})
        if offer.status != 'ACTIVE':
            return render(request, 'offer/init_transaction.html', {'offer': offer, 'error': 'Offer is not active'})
        
        Transaction.objects.create(offer=offer, buyer=request.user,coin=coin, status='PENDING', txid='')
        
        # * Perform transaction based on the coin and amount and the seller address and website address
        # TODO: Implement this function

localmonero/localmonero/templates/offer/new_offer.html
{% extends 'base.html' %}

{% block title %}New Offer{% endblock %}

{% block content %}
{% if error %}
    <p>{{ error }}</p>
{% endif %}
<h1>Create a New Offer</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Create Offer</button>
</form>
{% endblock %}

localmonero/localmonero/templates/offer/offer_detail.html
{% extends 'base.html' %}

{% block title %}Offer Detail{% endblock %}

{% block content %}
<h1>Offer Details</h1>
<p>Type: {{ offer.get_offer_type_display }}</p>
<p>Cryptocurrency: {{ offer.get_cryptocurrency_display }}</p>
<p>Amount: {{ offer.amount }}</p>
<p>Price: {{ offer.price }}</p>
<p>Details: {{ offer.details }}</p>

{% if offer.seller == request.user %}
    <a href="{% url 'offer:offer_edit' offer.id %}">Edit</a>
    <a href="{% url 'offer:offer_delete' offer.id %}">Delete</a>
{% else %}
    <a href="{% url 'offer:offer_buy' offer.id %}">Buy</a>
{% endif %}

{% endblock %}

localmonero/localmonero/templates/offer/offer_edit.html
{% extends 'base.html' %}

{% block title %}Edit Offer{% endblock %}

{% block content %}
<h1>Edit Offer</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>
{% endblock %}

localmonero/localmonero/templates/offer/offer_list.html
{% extends 'base.html' %}

{% block title %}Offer List{% endblock %}

{% block content %}
<h1>Offers</h1>
<a href="{% url 'offer:new_offer' %}">New Offer</a>
<a href="{% url 'offer:offer_search' %}">Search Offers</a>
<h3>{{ count }} offers found</h3>

<ul>
    {% for offer in offers %}
        <li>
            <a href="{% url 'offer:offer_detail' offer.id %}">{{ offer }}</a>
            {% if offer.seller == request.user %}
            <a href="{% url 'offer:offer_edit' offer.id %}">Edit</a>
            <a href="{% url 'offer:offer_delete' offer.id %}">Delete</a>
            {% endif %}
        </li>
    {% endfor %}
</ul>
{% endblock %}

localmonero/localmonero/templates/offer/offer_search.html
{% extends 'base.html' %}

{% block title %}New Offer{% endblock %}

{% block content %}
<h1>Search Offers</h1>
<form method="get">
    <input type="text" name="query" value="{{ query }}" placeholder="Search offers...">
    <button type="submit">Search</button>
</form>



{% if query %}<p>Results for "{{ query }}":</p>{% endif %}
<ul>
    {% for result in results %}
        <li><a href="{% url 'offer_detail' result.id %}">{{ result }}</a></li>
    {% endfor %}
</ul>

{% endblock %}